### ISSUE TITLE
`to` in DIDComm messages should be an array of DIDs

### ISSUE THREAD

**Issue by brianorwhatever** [decentralized-identity/waci-presentation-exchange#100]
As described in https://identity.foundation/didcomm-messaging/spec/#message-headers the `to` property in didcomm messages should be a list of dids containing the audience of the message (can be 1 or multiple)

Importantly this `to` isn't used for routing or encryption

**Comment by mirceanis** [comment]
I believe this would unnecessarily complicate the message sending and error handling logic.
There are exponentially more corner cases to cover with multiple recipients.

**Comment by brianorwhatever** [comment]
Yes it does add overhead however it's important to note this `to` field is not used for sending or routing of any kind. It is only used as contextual information for the receiver to know who else the message was sent to
