### ISSUE TITLE
Interop Testing

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/waci-presentation-exchange#138]
I suggest DIF organize something independently to achieve some results.

Potential timeline for supply chain traceability testing discussed here:

 https://github.com/w3c-ccg/traceability-interop/issues/17

**Comment by Identitywoman** [comment]
Hi @OR13 thanks for raising this issue. 
Indeed we within the DIF Interoperability Working Group are working discerning what we will be doing this coming winter/spring. 

There is interest in supporting Interop around JSON-LD ZKP with BBS+  along with  WACI-PEX 

Our first Interop meeting of the year is next Wednesday at 6am pacific 9am ET 
Here is our agenda - https://github.com/decentralized-identity/interoperability/blob/master/agenda.md
Please join us to discuss.

**Comment by OR13** [comment]
We need to open a new issue to track further interop work, if folks want to see changes, that issue should describe the changes folks want to see.
