### ISSUE TITLE
Swapping tech with Overlapping Layers

### ISSUE THREAD

**Issue by TelegramSam** [decentralized-identity/waci-presentation-exchange#14]
The original WACI proposal is an all-in-one stack. We are proposing a layer cake stack, where different external specs guide the function of each layer. If we desire pieces of the stack to be swapped out for other technologies, we should be careful to recognize that some replacements affect multiple layers. When combined, how should the replacement displace the matching layers?

For example: DIDComm covers transport, and the Present Proof protocol handles the process of requesting and receiving the presentation. For some SIOP implementations, SIOP functions as _both_ the transport and the protocol for credential presentation.

How does this affect our plans, and how the spec should be written?

**Comment by OR13** [comment]
I think we should cut the spec down to v0.1 reqs and then do a PR with the minimal layer cake diagram for v0.1

**Comment by brentzundel** [comment]
Discussed during a meeting 19 July 2021.
We feel this may be out of scope for this group at this time. Closing for now.
