### ISSUE TITLE
Pausing meetings for a few weeks

### ISSUE THREAD

**Issue by bumblefudge** [decentralized-identity/waci-presentation-exchange#147]
today on the call, we considered suspending regular meetings while we wait on implementations to test and from which to define test vectors or for spec-related issues and PRs to amass. SecureKey is working hard on the first major implementation of this profile and working on how it fits into the Aries test harness; they (and/or @brianorwhatever ) will signal to C&C WG chairs and/or @OR13 and @brentzundel when the next meeting should be. 

To be clear, the implementation work is still ongoing, but between all the upstream issues, the spec work is on pause, and thus the spec-editorial meetings.

**Comment by OR13** [comment]
We are unpausing these meetings
