### ISSUE TITLE
DIDComm Out of Band for Web to Web Wallet Interactions

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/waci-presentation-exchange#15]
@troyronda @TelegramSam I am creating this issue to track the various ways DIDComm __might__ work in a web to web scenario... noting that all of these options are on the table and that non of them are really this spec's job.

### DIDComm + CHAPI

https://w3c-ccg.github.io/credential-handler-api/

Allows a website to enable a user to pick a wallet to use to interact with the website.

This would allow a `controller` to pick the web wallet to respond to the first message provided by the verifier `message_0`.

### DIDComm + Protocol Handlers

- [message passing with protocol handler and query strings](https://github.com/OR13/didcomm-web-transports#protocol-handler-based-message-passing)

### DIDComm + Redirects

- [message passing with query strings from approved wallets only](https://github.com/OR13/didcomm-web-transports#query-string-based-message-passing)

### DIDComm + Deep Links

???

#### Critical Blocker for Web based interop

How does DIDComm handle communication between a verifier website and a prover http backend?

Links to existing draft proposals only please, this has to be feasible without inventing it "here".

**Comment by OR13** [comment]
The key problem is this:

given a page: https://example.com/verifier/presentations/inbox.html

how does a mobile web browser visiting this page submit a response to the JSON the verifier provides.

**Comment by brentzundel** [comment]
We would like this capability in v0.1, but recognize that time constraints may move it to v1

**Comment by OR13** [comment]
See also comments on https://github.com/w3c-ccg/universal-wallet-interop-spec/issues/99

**Comment by OR13** [comment]
Decision to remove the v0.1 label from this issue.

**Comment by OR13** [comment]
@troyronda feel free to resurrect this with a concrete proposal.

**Comment by rolsonquadras** [comment]
> tagging @troyronda and @sudeshrshetty
> 
> @sudeshrshetty has raised a PR [hyperledger/aries-rfcs#700](https://github.com/hyperledger/aries-rfcs/pull/700) in Aries-RFC repo for handling the Web-Web Redirect Scenario for DIDComm. Current plan is to get some community feedback and refine it. Once its accepted, add a appendix/note to DIDComm v2 and WACI spec linking to the DIDComm Web Redirect Spec.

The [Web Redirect](https://identity.foundation/didcomm-messaging/spec/#redirecting-back-to-sender) feature has been added to DIDComm v2 spec. I have created a [WACI PR](https://github.com/decentralized-identity/waci-presentation-exchange/pull/124) to add a section about DIDComm v2 redirect.

**Comment by OR13** [comment]
This is now better tracked on other issues / DIDComm v2.

**Comment by bumblefudge** [comment]
NB @dmitrizagidulin
