### ISSUE TITLE
Interoperability Profile - session 7.3 and 7.4's example are incorrect

### ISSUE THREAD

**Issue by echenknox** [decentralized-identity/waci-presentation-exchange#158]
In “[WACI-DIDComm Interop Profile](https://identity.foundation/waci-presentation-exchange/#abstract)” section 7.2 Presentation step 3.
The sequence diagram in section 6.2 Presentation describes this step is from `Verifier to Wallet`, but the example is:

```
  "from": "did:example:prover",
  "to": [
    "did:example:verifier"
  ],
```

The same as [step 4](https://identity.foundation/waci-presentation-exchange/#step-4-present-proof).

**Comment by echenknox** [comment]
It is reported and resolved here.
https://github.com/decentralized-identity/waci-didcomm/issues/10

**Comment by bumblefudge** [comment]
thanks @echenknox ! we discussed on yesterday's call
