### ISSUE TITLE
Update spec to include VaccinationCertificate frame in Presentation Definition object.

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/waci-presentation-exchange#18]
Add language to the spec that describes how folks should use a JSON-LD frame with PE spec data model.

original conversations about hypothetical alternatives here: https://github.com/decentralized-identity/waci-presentation-exchange/issues/6

**Comment by OR13** [comment]
Lets stick to the Permanent Resident card example for the first set of test vectors, this ticket can be closed when the spec provides the following examples:


```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/citizenship/v1",
    "https://w3id.org/bbs/v1"
  ],
  "type": ["VerifiableCredential", "PermanentResidentCard"],
  "credentialSubject": {
    "@explicit": true,
    "type": ["PermanentResident", "Person"],
    "givenName": {},
    "familyName": {}
  }
}
```

**Comment by brentzundel** [comment]
Implemented in linked PR, closing
