### ISSUE TITLE
Need v3 of Present Proof

### ISSUE THREAD

**Issue by TelegramSam** [decentralized-identity/waci-presentation-exchange#19]
v2 is here: https://github.com/hyperledger/aries-rfcs/tree/master/features/0454-present-proof-v2
Needs DIDComm V2 Message changes applied (including attachments)

**Comment by TelegramSam** [comment]
This includes adaptations for attachments (as they differ from DIDComm v1 and DIDComm v2) and basic message structure (like `@id` and `@type`).

**Comment by OR13** [comment]
I propose we just nest this in the v0.1 release of the spec, so we don't need to coordinate with another group.

**Comment by brentzundel** [comment]
All that is needed is to update the message formats from the link above, the rest of the markdown can be pretty much pasted in wholesale

**Comment by TelegramSam** [comment]
Doneski

**Comment by brentzundel** [comment]
closed by #54
