### ISSUE TITLE
Routing Key editorial todo (fka DID Doc Requirements)

### ISSUE THREAD

**Issue by TelegramSam** [decentralized-identity/waci-presentation-exchange#24]
DID and DID Document Requirements
DIDs can by any method that supports the required key types and a service block of the following format:

```
"service": [{
    "id": "#someid",
    "type": "didcommmessaging",
    "serviceEndpoint": "https://example.com/endpoint",
    "routingKeys": ["did:example:somemediator#somekey"]
  }]
```
If ledger reliance is an issue, Peer DIDs (particularly method 2) may be used.

**Comment by bumblefudge** [comment]
More guidance on the "ledger reliance" comment requested! Discuss in meeting?

**Comment by brianorwhatever** [comment]
closed during meeting on Jun 14

**Comment by OR13** [comment]
The action is to close out the TODO, regarding "what are routing keys"

**Comment by TelegramSam** [comment]
cleanup TODO Text surrounding routing keys
