### ISSUE TITLE
Editorial to-do - HTTP setup from DIDComm v2 needs to be summarized briefly (fka HTTP Transport Details)

### ISSUE THREAD

**Issue by TelegramSam** [decentralized-identity/waci-presentation-exchange#25]
we need to detail how the DID Doc requirements translate into HTTP Transport of messages.

Origin text in DIDComm spec: https://identity.foundation/didcomm-messaging/spec/#https

**Comment by bumblefudge** [comment]
Discuss tomorrow? Put a place-holder into my PR but I am way out of my depth here.

**Comment by brianorwhatever** [comment]
closed on call June 14th

**Comment by OR13** [comment]
Needs additional text, regarding use with HTTP endpoints, so that folks only need to read didcomm for fun.
