### ISSUE TITLE
WACI-PEx branding/pronunciation

### ISSUE THREAD

**Issue by bumblefudge** [decentralized-identity/waci-presentation-exchange#39]
CCG call today included a request for a new name and/or pronunciation with many +1s. There was also a general request for a clearer narrative about "convergence path"-- is this a way to help people negotiate a query-by-frame or a way to sidestep the VP Request spec at CCG?  I guess both of these are editorial decisions that might need to be taken at some point between v0.1 and v1? I defer to the group here, I don't have strong opinions on the former and don't know enough to formulate (much less take) a position on the latter.

**Comment by TelegramSam** [comment]
I think those opposed to the name should submit replacement name ideas.

**Comment by bumblefudge** [comment]
WACK-INT

**Comment by OR13** [comment]
Names are important, looks like we are stuck with WACI we'll try harder next time.
