### ISSUE TITLE
[DIDComm] Success/Redirection after Wallet Presentation Submission

### ISSUE THREAD

**Issue by rolsonquadras** [decentralized-identity/waci-presentation-exchange#40]
In Request/Share section, the [wallet receives an empty success response or a redirectURL](https://identity.foundation/waci-presentation-exchange/#response) when verifier validates the presentation_submission. 

But [in case of DIDComm](https://identity.foundation/waci-presentation-exchange/#message-2-present-proof), how would the wallet knows that the submission was successful or the redirectURL ? DIDComm [being transmit only](https://identity.foundation/didcomm-messaging/spec/#https), the http 202 indicates that the other agent has received the message and not essentially processed/validated it.

One solution would be to wait for [problem-report](https://github.com/hyperledger/aries-rfcs/blob/808daf80b7dbf084207a6c1627ce351247c90b78/features/0035-report-problem/README.md) from verifier with some timeout in wallet (not an ideal solution).

**Comment by OR13** [comment]
does the holder need a confirmation? if they do, another message is required.

**Comment by andrewwhitehead** [comment]
In [present-proof 2.0](https://github.com/hyperledger/aries-rfcs/tree/master/features/0454-present-proof-v2) the success indicator is an `ack-presentation` message.

**Comment by OR13** [comment]
@andrewwhitehead can you provide a complete example of the message.

**Comment by andrewwhitehead** [comment]
I think it would just be this:

```jsonc
{
    "@type": "https://didcomm.org/present-proof/2.0/ack",
    "~thread": {
        "thid": "ref-thread-id-00001",
    },
    "status": "OK"
}
```

**Comment by OR13** [comment]
^ needs to be DIDComm 2.0 format.

**Comment by andrewwhitehead** [comment]
Not sure whether it'd be thid or pthid, but I think it'd be something like this, possibly with the redirect URL added.

```jsonc
{
  "type": "https://didcomm.org/present-proof/3.0/ack",
  "id": "f1ca8245-ab2d-4d9c-8d7d-94bf310314ef",
  "pthid": "ref-thread-id-00001",
  "from": "did:example:verifier",
  "to": "did:example:prover",
  "body": {
    "status": "OK"
  }
}
```

**Comment by brianorwhatever** [comment]
pthid is right as per https://github.com/decentralized-identity/didcomm-messaging/pull/200
this ack message should be added to the spec

**Comment by kdenhartog** [comment]
@andrewwhitehead would it make sense to change the type to make it a more generalized message? So something like this (assuming I got the versioning right and that namespace hasn't already been used):

```json
{
  "type": "https://didcomm.org/ack/1.0",
  "id": "f1ca8245-ab2d-4d9c-8d7d-94bf310314ef",
  "pthid": "ref-thread-id-00001",
  "from": "did:example:verifier",
  "to": "did:example:prover",
  "body": {
    "status": "OK"
  }
}
```

**Comment by andrewwhitehead** [comment]
@kdenhartog  Acks are based on [Aries RFC 0015](https://github.com/hyperledger/aries-rfcs/tree/master/features/0015-acks) which suggests that the message may be adopted (and presumably extended) for specific protocols. This was done for present-proof 2.0. I can say that for our implementation in ACA-Py it's helpful to immediately know what protocol the ack was associated with.

**Comment by kdenhartog** [comment]
Sounds good thanks for weighing in on that. Based on what you described and your implementation experience with it, I think your solution is likely to be the better way to go.
