### ISSUE TITLE
The layer cake diagram is incomplete

### ISSUE THREAD

**Issue by brianorwhatever** [decentralized-identity/waci-presentation-exchange#42]
The presentation proposal needs a PE definition or else it's not proposing anything. I couldn't fork https://whimsical.com/XpEytT4XtKFDPSyHYP3JVj since I don't have access @bumblefudge

**Comment by brianorwhatever** [comment]
I also think we should include what direction each of the messages is going and label who is the prover and verifier unless that's now what this diagram is supposed to do. It's at the top of the document though so people who land here should be able to get what this spec does on that first impression

**Comment by bumblefudge** [comment]
Whoops, sorry about the permissions, shared the file live on the call and checked the wrong box.  should be forkable now

**Comment by bumblefudge** [comment]
Here's a mockup, which you should hopefully be able to fork and PR now:

![image](https://user-images.githubusercontent.com/37127325/122348764-cb957a80-cf4b-11eb-8b8b-5b5764150288.png)

**Comment by brianorwhatever** [comment]
yeah there should be an attachment I think or else theres no communication of what they are proposing.
it needs to be added here when we know what it is https://github.com/decentralized-identity/waci-presentation-exchange/pull/41

if that's the case what about something like this?
![image](https://user-images.githubusercontent.com/7122708/122351300-db3ca100-cf02-11eb-8c71-b20e0226103b.png)

**Comment by bumblefudge** [comment]
Way better, let's merge either with or without that msg 0 attachment as soon as #41 is decided (sorry I don't understand well enough to help with #41)

**Comment by brianorwhatever** [comment]
added to #41

**Comment by brianorwhatever** [comment]
discussed on Jun 21 call.
the propose message doesn't have an attachment it is simply a "i want to present something" message
