### ISSUE TITLE
End to end implementation

### ISSUE THREAD

**Issue by brianorwhatever** [decentralized-identity/waci-presentation-exchange#44]
I am planning on implementing this spec from scratch by the end of July. My plan to do so is the following:

- Use the `link` flow
- Use `did:web` to create a did with a service block that will work for DIDComm
- Implement DIDComm v2
    - [https://didcomm.org/present-proof/3.0/propose-presentation](https://didcomm.org/present-proof/3.0/propose-presentation)
    - [https://didcomm.org/present-proof/3.0/request-presentation](https://didcomm.org/present-proof/3.0/request-presentation)
        - Including JSON-LD Frame
    - [https://didcomm.org/present-proof/3.0/presentation](https://didcomm.org/present-proof/3.0/presentation)
        - BBS+ VC
- Implement DIF Presentation Exchange
    - Presentation Definition
    - Presentation Submission

Other than the QR code flow is there anything else that I am leaving off?

**Comment by OR13** [comment]
This is excellent, I would love to be able to do the same, it will be much easier to follow in your footsteps if I can.

I would suggest we specifically limit the X25519 and `ECDH-ES+A256KW` for DIDComm encryption.

We could also do P-256 `ECDH-ES+A256KW`... which would have the added benefit of being browser capable, and even more widely supported than X25519.... but its a NIST curve.

pinning down an answer to this and the presentation proof format would seem to be what is missing.

This is an example of what I believe a best minimal didDocument would look like:

```json
{
  "@context": [
    "https://www.w3.org/ns/did/v1",
    "https://w3id.org/security/suites/jws-2020/v1"
  ],
  "id": "did:web:example.com",
  "verificationMethod": [
    {
      "id": "did:web:example.com#key-0",
      "type": "JsonWebKey2020",
      "controller": "did:web:example.com",
      "publicKeyJwk": {
        "kty": "OKP",
        "crv": "Ed25519",
        "x": "O2onvM62pC1io6jQKm8Nc2UyFXcd4kOmOsBIoYtZ2ik"
      }
    },
    {
      "id": "did:web:example.com#key-1",
      "type": "JsonWebKey2020",
      "controller": "did:web:example.com",
      "publicKeyJwk": {
        "kty": "OKP",
        "crv": "X25519",
        "x": "W_Vcc7guviK-gPNDBmevVw-uJVamQV5rMNQGUwCqlH0"
      }
    },
    {
      "id": "did:web:example.com#key-g1",
      "controller": "did:web:example.com",
      "type": "JsonWebKey2020",
      "publicKeyJwk": {
        "kty": "EC",
        "crv": "BLS12381_G1",
        "x": "go_q7BgIP_fA-e55KEw8FSEdHGEBkzDGoDQhLZpE3im2MafjAp2aoQ649YkLbUUg"
      }
    },
    {
      "id": "did:web:example.com#key-g2",
      "controller": "did:web:example.com",
      "type": "JsonWebKey2020",
      "publicKeyJwk": {
        "kty": "EC",
        "crv": "BLS12381_G2",
        "x": "qovzgTVQFGdVgUVBCV8cuhinO4tMVSUpvh8kh7m_z6DJ4NfzJ5ffBFGbp-VVgHksEEdgOMh2hUjplsMFV0FYVsiQqQLjCmrfr_pRDZ60Q1vURzptp3dQbcAE_wvXGKLe"
      }
    }
  ],
  "assertionMethod": [
    "did:web:example.com#key-0",
    "did:web:example.com#key-g2"
  ],
  "authentication": ["did:web:example.com#key-0"],
  "keyAgreement": ["did:web:example.com#key-1"],
  "service": [
    {
      "id": "did:web:example.com#agent-0",
      "type": "DIDCommMessaging",
      "serviceEndpoint": "https://agent-0.example.com/endpoint",
      "routingKeys": ["did:web:example.com#key-0"]
    }
  ]
}
```

Not that it could be smaller if we are willing to use NIST curves...

```
{
  "@context": [
    "https://www.w3.org/ns/did/v1",
    "https://w3id.org/security/suites/jws-2020/v1"
  ],
  "id": "did:web:example.com",
  "verificationMethod": [
    {
      "id": "did:web:example.com#key-0",
      "type": "JsonWebKey2020",
      "controller": "did:web:example.com",
      "publicKeyJwk": {
        "kty": "EC",
        "crv": "P-256",
        "x": "8a42OinFJqhRUpykae_P_VhkXGAJPGHucT2RJT_cRU8",
        "y": "V9sdHXkCgnlxgMqZNB-n5MMCNVPX_3YGAaEb3wZjjQI"
      }
    },
    {
      "id": "did:web:example.com#key-g1",
      "controller": "did:web:example.com",
      "type": "JsonWebKey2020",
      "publicKeyJwk": {
        "kty": "EC",
        "crv": "BLS12381_G1",
        "x": "go_q7BgIP_fA-e55KEw8FSEdHGEBkzDGoDQhLZpE3im2MafjAp2aoQ649YkLbUUg"
      }
    },
    {
      "id": "did:web:example.com#key-g2",
      "controller": "did:web:example.com",
      "type": "JsonWebKey2020",
      "publicKeyJwk": {
        "kty": "EC",
        "crv": "BLS12381_G2",
        "x": "qovzgTVQFGdVgUVBCV8cuhinO4tMVSUpvh8kh7m_z6DJ4NfzJ5ffBFGbp-VVgHksEEdgOMh2hUjplsMFV0FYVsiQqQLjCmrfr_pRDZ60Q1vURzptp3dQbcAE_wvXGKLe"
      }
    }
  ],
  "assertionMethod": [
    "did:web:example.com#key-0",
    "did:web:example.com#key-g2"
  ],
  "authentication": ["did:web:example.com#key-0"],
  "keyAgreement": ["did:web:example.com#key-0"],
  "service": [
    {
      "id": "did:web:example.com#agent-0",
      "type": "DIDCommMessaging",
      "serviceEndpoint": "https://agent-0.example.com/endpoint",
      "routingKeys": ["did:web:example.com#key-0"]
    }
  ]
}

```

**Comment by bumblefudge** [comment]
Not to be a wet blanket, but I think the DIDComm group deprecated P-256 in favor of P-384 a few months back, although I think all the currently-existing implementations that support P-384 might still support P-256:

https://identity.foundation/didcomm-messaging/spec/#curves-and-content-encryption-algorithms
https://github.com/decentralized-identity/didcomm-messaging/pull/166

**Comment by brianorwhatever** [comment]
Excellent I will publish my implementation repo early next week. I will be a bit more comfortable figuring out the didcomm stuff and might need a hand with the PE stuff. I did find that tool Daniel showed in the last 2 mins of the last DIF interop meeting which might help there. The fact that the LD suites aren’t in there yet shows how 2nd class of a citizen they are though so I’m worried in that regard.

Re: your questions
1. Isn’t the issuance from a different DID? This is more the flow between a holder and verifier isn’t it?
2. Does it matter?
3. Will try to figure this out but what the heck is a 1-PU? Is it just the same crypto but the encrypted message is signed as well?

Question for you: How come JWKs are preferable? For Jose/jwt things I assume? I’ve been using publickeybase58 up until now

**Comment by OR13** [comment]
> 1. Isn’t the issuance from a different DID? This is more the flow between a holder and verifier isn’t it?

yes, you are correct. You will still need a valid VC to test though, your code will need to be able to verify the issued credential as part of verifying the presentation.
> 3. Will try to figure this out but what the heck is a 1-PU? Is it just the same crypto but the encrypted message is signed as well?

ECDH-1PU should be ignored for spec v0.1, this was agreed to on multiple calls. You should focus on ECDH-ES for v0.1.


> Question for you: How come JWKs are preferable? For Jose/jwt things I assume? I’ve been using publickeybase58 up until now

JWKs are preferable any time you are using JOSE... since they are defined by JOSE... otherwise you will be converting to JWK every time you want to do anything with off the shelf tooling for JOSE

**Comment by brianorwhatever** [comment]
Ok I have a basic implementation of did:web working that outputs a document that matches your example above. I am working on this at https://github.com/aviarytech/wacinsteins-monster

Anyone is welcome to contribute over there it's a total sandbox (with in memory keys...)

I recommend closing this issue during the next call.

**Comment by OR13** [comment]
Discussed on the call, recommend closing.
