### ISSUE TITLE
Example Completeness questions

### ISSUE THREAD

**Issue by bumblefudge** [decentralized-identity/waci-presentation-exchange#45]
As per this week's call and a comment on a separate issue (https://github.com/decentralized-identity/waci-presentation-exchange/issues/35#issuecomment-861014233), I am creating this issue to track the example completeness in the DIDComm v2 messages section.  I assume multiple PRs will be needed to close this issue :D

Some questions I had when trying to PR in some threading and make all the `id`s match/refer to one another:

1. is a completely empty `body` valid on L672 (msg1) and L752 (msg2)? I didn't see any empty `body`s in the DIDComm spec, but I didn't see any normative text proscribing them either :)

2. is an empty `body` preferable? no dog in this fight, just floating it in case normative and/or non-normative text and/or an illustrative example would make this clearer to didcomm newbs encountering this. 

3. should msg0 have a pthid pointing to an invitation msg (msg -1? oob0?) or is msg0 the invitation?

**Comment by kdenhartog** [comment]
> is a completely empty body valid on L672 (msg1) and L752 (msg2)? I didn't see any empty bodys in the DIDComm spec, but I didn't see any normative text proscribing them either :)

I'd say yeah it's fine. This is a common pattern that Signal uses as well which is to utilize the same messaging layer between their application and metadata about messages at the application layer (e.g. key rotations/notifications/etc)

>is an empty body preferable? no dog in this fight, just floating it in case normative and/or non-normative text and/or an illustrative example would make this clearer to didcomm newbs encountering this.

Sorry to answer a question with a question here, but wanting to make sure I'm offering good information. Is there a way that we could combine it with another message? The fewer messages we send the more reliable things tend to be.

> should msg0 have a pthid pointing to an invitation msg (msg -1? oob0?) or is msg0 the invitation?
I'll defer this to @troyronda @swcurran or @TelegramSam who are more familiar with how OOB gets integrated these days. I'm of the opinion this OOB message likely isn't necessary, but in the case it's kept will defer to their judgement.

**Comment by brentzundel** [comment]
discussed during 26 July call, consensus is that this has been addressed.
