### ISSUE TITLE
Update DIDComm messages to match v2

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/waci-presentation-exchange#5]
See https://github.com/decentralized-identity/waci-presentation-exchange/pull/4#pullrequestreview-648085501

**Comment by brentzundel** [comment]
@telegramsam has agreed to be assigned

**Comment by OR13** [comment]
Any update on this? AFAIK the DIDComm Messages are the most critical blocker here.

**Comment by brentzundel** [comment]
better handled by other issues, closing
