### ISSUE TITLE
Usage of 0-RTT for Message 1

### ISSUE THREAD

**Issue by kdenhartog** [decentralized-identity/waci-presentation-exchange#51]
Hey I noticed that right now we've got the Message -1 as an OOB 2.0 message which is useful for setting up a connection. However because of the usage of 0-RTT in DIDCommV2 it should be possible to utilize Message 0 directly to both initiate the connection and start the flow. I looked through the old issues and didn't see anyone mention this as a possible option. Was it considered and ruled out as in-viable for some reason? If so what was it?

**Comment by brianorwhatever** [comment]
on the call today we talked about changing everything to steps and they start from 1 see #49 and #50

**Comment by bumblefudge** [comment]
Is "Step 1"/"Message -1" completely optional doing "Step 2"/"Message 0" differently, or would skipping step 1 require a different, alternate step 1, i.e., `Step 1'` ? 😄

**Comment by kdenhartog** [comment]
Yeah essentially because of 0-RTT you should be able to skip Step 1/Message -1 (The OOB message)

So my question is more around whether it was chosen not to do that, and if so what was the reason?

**Comment by kdenhartog** [comment]
> 
> 
> Is "Step 1"/"Message -1" completely optional doing "Step 2"/"Message 0" differently, or would skipping step 1 require a different, alternate step 1, i.e., `Step 1'` ? 😄

I just realized I think Step -1, Step 0, and Step 2 can all be rolled together. Basically you just do this:

Take the JSON in the request:

```json
{
  "type": "https://didcomm.org/present-proof/3.0/request-presentation",
  "id": "0ac534c8-98ed-4fe3-8a41-3600775e1e92",
  "thid": "95e63a5f-73e1-46ac-b269-48bb22591bfa",
  "from": "did:example:prover",
  "to": "did:example:verifier",
  "body": {},
  "attachments": [
    {
      "@id": "ed7d9b1f-9eed-4bde-b81c-3aa7485cf947",
      "mime-type": "application/json",
      "format": "dif/presentation-exchange/definitions@v1.0",
      "data": {
        "json": {
          "dif": {
            "options": {
              "challenge": "3fa85f64-5717-4562-b3fc-2c963f66afa7",
              "domain": "4jt78h47fh47"
            },
            "presentation_definition": {
              "id": "32f54163-7166-48f1-93d8-ff217bdb0654",
              "frame": {
                "@context": [
                  "https://www.w3.org/2018/credentials/v1",
                  "https://w3id.org/vaccination/v1",
                  "https://w3id.org/security/suites/bls12381-2020/v1"
                ],
                "type": [
                  "VerifiableCredential",
                  "VaccinationCertificate"
                ],
                "credentialSubject": {
                  "@explicit": true,
                  "type": [
                    "VaccinationEvent"
                  ],
                  "batchNumber": {},
                  "countryOfVaccination": {}
                }
              },
              "input_descriptors": [
                {
                  "id": "vaccination_input",
                  "name": "Vaccination Certificate",
                  "schema": "https://w3id.org/vaccination/#VaccinationCertificate",
                  "constraints": {
                    "fields": [
                      {
                        "path": [
                          "$.credentialSubject.batchNumber"
                        ],
                        "filter": {
                          "type": "string"
                        }
                      },
                      {
                        "path": [
                          "$.credentialSubject.countryOfVaccination"
                        ],
                        "filter": {
                          "type": "string"
                        }
                      }
                    ]
                  }
                }
              ]
            }
          }
        }
      }
    }
  ]
}
```

base64url encode it
`
eyJ0eXBlIjoiaHR0cHM6Ly9kaWRjb21tLm9yZy9wcmVzZW50LXByb29mLzMuMC9yZXF1ZXN0LXByZXNlbnRhdGlvbiIsImlkIjoiMGFjNTM0YzgtOThlZC00ZmUzLThhNDEtMzYwMDc3NWUxZTkyIiwidGhpZCI6Ijk1ZTYzYTVmLTczZTEtNDZhYy1iMjY5LTQ4YmIyMjU5MWJmYSIsImZyb20iOiJkaWQ6ZXhhbXBsZTpwcm92ZXIiLCJ0byI6ImRpZDpleGFtcGxlOnZlcmlmaWVyIiwiYm9keSI6e30sImF0dGFjaG1lbnRzIjpbeyJAaWQiOiJlZDdkOWIxZi05ZWVkLTRiZGUtYjgxYy0zYWE3NDg1Y2Y5NDciLCJtaW1lLXR5cGUiOiJhcHBsaWNhdGlvbi9qc29uIiwiZm9ybWF0IjoiZGlmL3ByZXNlbnRhdGlvbi1leGNoYW5nZS9kZWZpbml0aW9uc0B2MS4wIiwiZGF0YSI6eyJqc29uIjp7ImRpZiI6eyJvcHRpb25zIjp7ImNoYWxsZW5nZSI6IjNmYTg1ZjY0LTU3MTctNDU2Mi1iM2ZjLTJjOTYzZjY2YWZhNyIsImRvbWFpbiI6IjRqdDc4aDQ3Zmg0NyJ9LCJwcmVzZW50YXRpb25fZGVmaW5pdGlvbiI6eyJpZCI6IjMyZjU0MTYzLTcxNjYtNDhmMS05M2Q4LWZmMjE3YmRiMDY1NCIsImZyYW1lIjp7IkBjb250ZXh0IjpbImh0dHBzOi8vd3d3LnczLm9yZy8yMDE4L2NyZWRlbnRpYWxzL3YxIiwiaHR0cHM6Ly93M2lkLm9yZy92YWNjaW5hdGlvbi92MSIsImh0dHBzOi8vdzNpZC5vcmcvc2VjdXJpdHkvc3VpdGVzL2JsczEyMzgxLTIwMjAvdjEiXSwidHlwZSI6WyJWZXJpZmlhYmxlQ3JlZGVudGlhbCIsIlZhY2NpbmF0aW9uQ2VydGlmaWNhdGUiXSwiY3JlZGVudGlhbFN1YmplY3QiOnsiQGV4cGxpY2l0Ijp0cnVlLCJ0eXBlIjpbIlZhY2NpbmF0aW9uRXZlbnQiXSwiYmF0Y2hOdW1iZXIiOnt9LCJjb3VudHJ5T2ZWYWNjaW5hdGlvbiI6e319fSwiaW5wdXRfZGVzY3JpcHRvcnMiOlt7ImlkIjoidmFjY2luYXRpb25faW5wdXQiLCJuYW1lIjoiVmFjY2luYXRpb24gQ2VydGlmaWNhdGUiLCJzY2hlbWEiOiJodHRwczovL3czaWQub3JnL3ZhY2NpbmF0aW9uLyNWYWNjaW5hdGlvbkNlcnRpZmljYXRlIiwiY29uc3RyYWludHMiOnsiZmllbGRzIjpbeyJwYXRoIjpbIiQuY3JlZGVudGlhbFN1YmplY3QuYmF0Y2hOdW1iZXIiXSwiZmlsdGVyIjp7InR5cGUiOiJzdHJpbmcifX0seyJwYXRoIjpbIiQuY3JlZGVudGlhbFN1YmplY3QuY291bnRyeU9mVmFjY2luYXRpb24iXSwiZmlsdGVyIjp7InR5cGUiOiJzdHJpbmcifX1dfX1dfX19fX1dfQ
`

and combine it all into a URL

`https://example.com/some/path?_oob=eyJ0eXBlIjoiaHR0cHM6Ly9kaWRjb21tLm9yZy9wcmVzZW50LXByb29mLzMuMC9yZXF1ZXN0LXByZXNlbnRhdGlvbiIsImlkIjoiMGFjNTM0YzgtOThlZC00ZmUzLThhNDEtMzYwMDc3NWUxZTkyIiwidGhpZCI6Ijk1ZTYzYTVmLTczZTEtNDZhYy1iMjY5LTQ4YmIyMjU5MWJmYSIsImZyb20iOiJkaWQ6ZXhhbXBsZTpwcm92ZXIiLCJ0byI6ImRpZDpleGFtcGxlOnZlcmlmaWVyIiwiYm9keSI6e30sImF0dGFjaG1lbnRzIjpbeyJAaWQiOiJlZDdkOWIxZi05ZWVkLTRiZGUtYjgxYy0zYWE3NDg1Y2Y5NDciLCJtaW1lLXR5cGUiOiJhcHBsaWNhdGlvbi9qc29uIiwiZm9ybWF0IjoiZGlmL3ByZXNlbnRhdGlvbi1leGNoYW5nZS9kZWZpbml0aW9uc0B2MS4wIiwiZGF0YSI6eyJqc29uIjp7ImRpZiI6eyJvcHRpb25zIjp7ImNoYWxsZW5nZSI6IjNmYTg1ZjY0LTU3MTctNDU2Mi1iM2ZjLTJjOTYzZjY2YWZhNyIsImRvbWFpbiI6IjRqdDc4aDQ3Zmg0NyJ9LCJwcmVzZW50YXRpb25fZGVmaW5pdGlvbiI6eyJpZCI6IjMyZjU0MTYzLTcxNjYtNDhmMS05M2Q4LWZmMjE3YmRiMDY1NCIsImZyYW1lIjp7IkBjb250ZXh0IjpbImh0dHBzOi8vd3d3LnczLm9yZy8yMDE4L2NyZWRlbnRpYWxzL3YxIiwiaHR0cHM6Ly93M2lkLm9yZy92YWNjaW5hdGlvbi92MSIsImh0dHBzOi8vdzNpZC5vcmcvc2VjdXJpdHkvc3VpdGVzL2JsczEyMzgxLTIwMjAvdjEiXSwidHlwZSI6WyJWZXJpZmlhYmxlQ3JlZGVudGlhbCIsIlZhY2NpbmF0aW9uQ2VydGlmaWNhdGUiXSwiY3JlZGVudGlhbFN1YmplY3QiOnsiQGV4cGxpY2l0Ijp0cnVlLCJ0eXBlIjpbIlZhY2NpbmF0aW9uRXZlbnQiXSwiYmF0Y2hOdW1iZXIiOnt9LCJjb3VudHJ5T2ZWYWNjaW5hdGlvbiI6e319fSwiaW5wdXRfZGVzY3JpcHRvcnMiOlt7ImlkIjoidmFjY2luYXRpb25faW5wdXQiLCJuYW1lIjoiVmFjY2luYXRpb24gQ2VydGlmaWNhdGUiLCJzY2hlbWEiOiJodHRwczovL3czaWQub3JnL3ZhY2NpbmF0aW9uLyNWYWNjaW5hdGlvbkNlcnRpZmljYXRlIiwiY29uc3RyYWludHMiOnsiZmllbGRzIjpbeyJwYXRoIjpbIiQuY3JlZGVudGlhbFN1YmplY3QuYmF0Y2hOdW1iZXIiXSwiZmlsdGVyIjp7InR5cGUiOiJzdHJpbmcifX0seyJwYXRoIjpbIiQuY3JlZGVudGlhbFN1YmplY3QuY291bnRyeU9mVmFjY2luYXRpb24iXSwiZmlsdGVyIjp7InR5cGUiOiJzdHJpbmcifX1dfX1dfX19fX1dfQ`

Then the holder response continues as defined today.

Given the Proof of DID ownership is provable via the verifiable presentation as well, I'm not even certain we need all the token aspects as well. I need to think on that part a bit more though.

**Comment by brianorwhatever** [comment]
I like where Kyle is going here and am looking forward to hearing more of the groups opinion. @kdenhartog this would result in a 2 step process right? Request / Present

**Comment by troyronda** [comment]
@kdenhartog How did you determine both `from` and `to` in the example request? I think you only know the `from` without some prior message being involved.

- OOB sets up a broadcast to anyone `from` the verifier.
- Propose presentation tells the Verifier who is the holder (which will then be populated into `to`).
- Request presentation can then have both a `from` and a `to`.

**Comment by brianorwhatever** [comment]
also aren't the current examples in the spec backwards?
https://identity.foundation/waci-presentation-exchange/#message-1-request-presentation
request has a `from` of prover and a `to` of verifier where the message is going in the other direction.
message 2 (present) has the same problem but in reverse

**Comment by kdenhartog** [comment]
> @kdenhartog How did you determine both `from` and `to` in the example request? I think you only know the `from` without some prior message being involved.
> 
>     * OOB sets up a broadcast to anyone `from` the verifier.
> 
>     * Propose presentation tells the Verifier who is the holder (which will then be populated into `to`).
> 
>     * Request presentation can then have both a `from` and a `to`.

Shouldn't we be able to use the `skid` and `kid` properties on the outter envelope now? Before that 0-RTT was acheived through the usage of the from internally and the kid's externally.

**Comment by OR13** [comment]
I am not up to date with DIDComm V2 enough to really comment on this, but:

1. we should seek to reduce the number of messages
2. we should avoid mutual authentication

presentations are unidirectional authentication (holder authenticates with verifier).

**Comment by brentzundel** [comment]
For v0.1, separate QR code into generation (step 0) and holder scans QR code (step 1)

**Comment by TelegramSam** [comment]
I like the goal, but there are a number of challenges to reducing message count:
1. QR code size, without resorting to some other complexity like a shortener.
2. QR code may be printed, which means the longer flow must be used. Now we have two flows? (going for simple here, even if that means not most efficient in all cases.)
3. It doesn't allow for any accept-type negotiation (this is really a DIDComm v2 consideration, but implications may cascade with the success of this spec.)

**Comment by brentzundel** [comment]
@kdenhartog we discussed this in our meeting on 26 July and the group want to close the issue with no action
Do you have a response to Sam's comments above?

**Comment by kdenhartog** [comment]
I've not been tracking this well enough at this point to respond. Originally, this issue was intended to just be a feature suggestion for optimization. I'm good with closing this with no action and if someone wishes take the time to optimize the number of messages in the future at least this is here with some ideas.
