### ISSUE TITLE
Should delegation be disabled?

### ISSUE THREAD

**Issue by kdenhartog** [decentralized-identity/waci-presentation-exchange#56]
This is related to conversations that are ongoing in the CCG. However, given this is intended to be used for vaccination passes there's some odd behaviors that can arise from delegation. I think for the case of how the verifier is processing the VP response in the particular GHP use case we'll want to disable it. However, I'm not sure this is the right place to define it since in other use cases implementors may want to enable these capabilities.

What's people's thoughts on where this should be defined so that implementors get the verification process right and don't in advertently introduce issues from delegation of VCs/DIDs.

**Comment by OR13** [comment]
https://www.w3.org/TR/vc-data-model/#subject-holder-relationships

**Comment by OR13** [comment]
IMO, this is an application / business layer concern for GHP or other governance layers.

**Comment by OR13** [comment]
@kdenhartog advised us to close this issue on the call.

**Comment by bumblefudge** [comment]
Some points made on today's call:
* Orie: this inherits problems from the BBS+ and GHP business logic - this profile need not solve all the problems
* Kyle: Governance layer needs to decide/constrain delegation, perhaps
* Orie: Might be worth re-opening for v1?
* Kyle: Close it
* Orie: I'd cross link it later... tho
