### ISSUE TITLE
Invalid input JSON Schema Filter - no signal

### ISSUE THREAD

**Issue by henkvancann** [decentralized-identity/waci-presentation-exchange#57]
Testing Presentation Exchange repo: https://identity.foundation/presentation-exchange/playground/

Under Input descriptors ->  Fields -> JSON Schema Filter

See attachments, invalid input leads to deleting of "filter" attribute / line, but without a signal / warming that it's invalid input that triggers this.

<img width="1195" alt="Screenshot 2021-06-28 at 22 22 13" src="https://user-images.githubusercontent.com/479356/123700423-be885d80-d860-11eb-97d1-20887e1b1226.png">
<img width="1167" alt="Screenshot 2021-06-28 at 22 22 26" src="https://user-images.githubusercontent.com/479356/123700432-c0eab780-d860-11eb-8256-56a2a0696478.png">

**Comment by OR13** [comment]
We think this may be the wrong repo. discussed on the call.

**Comment by henkvancann** [comment]
ah sorry, what's the right one?

**Comment by csuwildcat** [comment]
@henkvancann this should go into the PE repo

**Comment by henkvancann** [comment]
https://github.com/decentralized-identity/presentation-exchange got it
