### ISSUE TITLE
Out of scope issue: ECDH-1PU caveat

### ISSUE THREAD

**Issue by bumblefudge** [decentralized-identity/waci-presentation-exchange#59]
The group asked today what needs a brief paragraph or two added to the "Out of scope" section at the very end.  One such iteas was Authenticated Encryption - specifically, the situation where ECDH-PU drafts are currently unstable (deferred while that gets worked out).

 @troyronda @dhh1128 would either of you wanna PR in a tiny blurb about why AuthN'd encryption is temporarily out of scope for WACI-PEx?

**Comment by TelegramSam** [comment]
ECDH-ES is common and in most libraries. DIDComm V2 uses ECDH-1PU (now at draft 4), but is not as settled as we need for v0.1. For future versions we will revisit.
