### ISSUE TITLE
We need a layer cake diagram

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/waci-presentation-exchange#8]
It should cover, DIDComm, HTTP, QRCodes.

It should but in context, things like JWE wrapper, HTTP URLs vs responses.

**Comment by brentzundel** [comment]
@csuwildcat will make the first attempt

**Comment by OR13** [comment]
Related: https://github.com/decentralized-identity/waci-presentation-exchange/issues/14

**Comment by TelegramSam** [comment]
![chrome_2021-06-07_14-17-55](https://user-images.githubusercontent.com/411919/121082396-45cf3d80-c79b-11eb-9fe2-dcf4a8eeb8d1.png)

This can be a starting place for the diagram.

**Comment by brianorwhatever** [comment]
I changed the DIDComm to be the envelope and included Presentation Exchange. What other protocols are there that I should add? Credential Manifest isn't a DIDComm protocol but it should be in there right?
![image](https://user-images.githubusercontent.com/7122708/121768916-afda4080-cb15-11eb-90be-b1393e87e214.png)

**Comment by brianorwhatever** [comment]
![image](https://user-images.githubusercontent.com/7122708/121769187-114edf00-cb17-11eb-9783-a9cfc5e87f40.png)

**Comment by OR13** [comment]
I think we should add the latest image to the spec, and open close this issue.

There will always be opportunities for better diagrams, but this is better than what we have today, we should get it into the spec.

**Comment by bumblefudge** [comment]
![image](https://user-images.githubusercontent.com/37127325/121956266-36369280-cd61-11eb-8311-739061704c32.png)
how's this?

**Comment by bumblefudge** [comment]
https://whimsical.com/XpEytT4XtKFDPSyHYP3JVj
^ feel free to fork and edit if you're a whimsical user

**Comment by bumblefudge** [comment]
![image](https://user-images.githubusercontent.com/37127325/121959715-6e3fd480-cd65-11eb-95ad-b30ee893d9b7.png)
 reeeemiiiiixx

**Comment by OR13** [comment]
@bumblefudge you are a god of live edits
