### ISSUE TITLE
WACI flow diagram needs updating

### ISSUE THREAD

**Issue by brentzundel** [decentralized-identity/waci-presentation-exchange#85]
The flow diagram in the WACI context should be updated to match the existing examples and flow of the spec.

**Comment by bumblefudge** [comment]
https://swimlanes.io/d/C5HnpvA4f

feel free to apply changes directly to the source and PR in new versions without me in future WG meetings

**Comment by bumblefudge** [comment]
ack tried recreating in mermaid mode and don't have the time this week, will just PR in a PNG for now, will try again on V1 timeline.  would rather have something in before review at CCG and/or interop WG

**Comment by OR13** [comment]
PR was added, but rendering is currently broken.

**Comment by brentzundel** [comment]
looks like rendering is working. Closing.
