### ISSUE TITLE
Editorial nit: thid/pthid still a smidge confusing

### ISSUE THREAD

**Issue by bumblefudge** [decentralized-identity/waci-presentation-exchange#90]
feel free to summarily close this issue without my consent/confirmation if I'm wrong about this, but my hunch is that the example in [this section](https://identity.foundation/waci-presentation-exchange/#step-2-send-message-proposing-presentation) should either
1.) have a `thid` instead of `pthid`, or 
2.) update its text to explain why it's `pthid` instead of `thid`.  

The latter makes more sense to me (the OOB invite is a prolific parent but not really the id to use as thid for all future messages, for that the id of the first message on a per-user channel answering the invite makes more sense), so maybe the text there should explain the pthid/thid distinction?  feel free to assign this to me, with the full warning that I can barely explain the difference between DIDComm v2 and two tin cans connected by twine.

**Comment by OR13** [comment]
PROPOSAL, define and example this:

```
"pthid": "599f3638-b563-4937-9487-dfe55099d900",
```

**Comment by OR13** [comment]
also cleanup `thid`...

> Note: ids MAY be any arbitrary string used to identify each message, such as a UUID or a hash, but the id of the initial message SHOULD be included as thid (“thread id”). In the above example, the id of the message that established a connection was used for thid; thid MAY be unspecified if this message is the first one over the channel or if a connection had been established out of band.

**Comment by OR13** [comment]
explain like I am 5 `thid`, `pthid`.
