### ISSUE TITLE
v1 Release Checklist

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/waci-presentation-exchange#94]
Deferred v1
- [x] Example annotation (line numbers and relevant spec references by line-range as per #35 )
- [x] link to sample implementation that actually work (reviewable code)
- [x] integration tests
    * Who will double-check the crypto libraries/dependencies stuff?

**Comment by OR13** [comment]
@brianorwhatever can you consider a PR that adds a link to your work so we can check these boxes.

**Comment by bumblefudge** [comment]
https://github.com/aviarytech/wacinsteins-monster

**Comment by OR13** [comment]
Should be addressed by https://github.com/decentralized-identity/waci-presentation-exchange/pull/128/files

**Comment by OR13** [comment]
I think this issue may no longer represent our intentions for v1 release.

**Comment by OR13** [comment]
We need editorial review of issuance flows, and full test vectors from AFG.
