### ISSUE TITLE
format in presentation_submission example

### ISSUE THREAD

**Issue by tlodderstedt** [decentralized-identity/waci-presentation-exchange#98]
The spec's example in "Step 4 - Present Proof" uses format="ldp_vp", but the path refers to the credential. So I would assume the format should be "ldp_vc".

**Comment by TomCJones** [comment]
I have never heard a valid use case for including any credential in an id token and continue to be against it on principle. The whole point of the credential was to hide information from the RP not to expose it.

**Comment by tlodderstedt** [comment]
How is your comment related to this issue?

**Comment by brianorwhatever** [comment]
The path refers to the first element of the `verifiableCredential` array which is inside of the VP

>  "path": "$.verifiableCredential[0]"

**Comment by OR13** [comment]
The format is correct, ti should b `ldp_vp` and inside that there will be a BBS+ `ldp_vc` which was derived according to the frame, and which has the correct input descroptions.

**Comment by OR13** [comment]
Closing, feel free to use the discussions feature to ask other questions.
